// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxqmaZPmGzXmkXrn8ef6EO8iRfDHy9vR4',
    appId: '1:296900597500:web:4ae1389954166806dea979',
    messagingSenderId: '296900597500',
    projectId: 'solar-e1840',
    authDomain: 'solar-e1840.firebaseapp.com',
    databaseURL: 'https://solar-e1840-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-e1840.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6RKP8_Aj2DlIu_A_5ewM2oB7FMvqYdSI',
    appId: '1:296900597500:android:e73dab2bf509867edea979',
    messagingSenderId: '296900597500',
    projectId: 'solar-e1840',
    databaseURL: 'https://solar-e1840-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-e1840.firebasestorage.app',
  );

}